services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: cipher-php
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/backend
      - ~/.ssh:/root/.ssh:ro
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
    environment:
      DATABASE_URL: postgresql://app:secret@database:5432/cipher?serverVersion=16&charset=utf8
      SSH_AUTH_SOCK: /ssh-agent
    depends_on:
      database:
        condition: service_healthy
    networks:
      - cipher-network

  database:
    image: postgres:16-alpine
    container_name: cipher-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cipher
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "cipher", "-U", "app"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - cipher-network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cipher-cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      database:
        condition: service_healthy
    networks:
      - cipher-network

volumes:
  database_data:
  cloudbeaver_data:

networks:
  cipher-network:
    driver: bridge
